src/CarpeDeumBundle/Entity/GeolocalizableInterface.php
<?php

namespace CarpeDeumBundle\Entity;

interface GeolocalizableInterface
{
    /**
     * @param GeolocalizableInterface $geolocalizable
     *
     * @return float
     */
    public function calculateDistance(self $geolocalizable);

    /**
     * @return array
     */
    public function getPosition();

    /**
     * @return float
     */
    public function getLongitude();

    /**
     * @return float
     */
    public function getLatitude();

    /**
     * @return string
     */
    public function getGeoPoint();
}

src/CarpeDeumBundle/Entity/Place.php
<?php

namespace CarpeDeumBundle\Entity;

use CarpeDeumBundle\Entity\Traits\GeolocalizableTrait;
use CarpeDeumBundle\Entity\Traits\TimestampableTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Sylius\Component\Resource\Model\ResourceInterface;

/**
 * Place.
 *
 * @ORM\Table(name="place")
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks()
 */
class Place implements GeolocalizableInterface, ResourceInterface
{
    use TimestampableTrait;
    use GeolocalizableTrait;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="bigint", options={"unsigned"=true})
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=100)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="type", type="string")
     */
    private $type = 'CHURCH';

    /**
     * @var string
     *
     * @ORM\Column(name="pic", type="string", length=200)
     */
    private $pic = '';

    /**
     * @var string
     *
     * @ORM\Column(name="pic_credits", type="text", nullable=true)
     */
    private $picCredits;

    /**
     * @var string
     *
     * @ORM\Column(name="pics", type="text", nullable=true)
     */
    private $pics;

    /**
     * @var string
     *
     * @ORM\Column(name="pics_list", type="text", nullable=true)
     */
    private $picsList;

    /**
     * @var string
     *
     * @ORM\Column(name="vids", type="text", nullable=true)
     */
    private $vids;

    /**
     * @var string
     *
     * @ORM\Column(name="vids_list", type="text", nullable=true)
     */
    private $vidsList;

    /**
     * @var string
     *
     * @ORM\Column(name="address", type="text")
     */
    private $address;

    /**
     * @var string
     *
     * @ORM\Column(name="address_1", type="text")
     */
    private $address1;

    /**
     * @var string
     *
     * @ORM\Column(name="address_2", type="text", nullable=true)
     */
    private $address2;

    /**
     * @var string
     *
     * @ORM\Column(name="zip_code", type="text")
     */
    private $zipCode;

    /**
     * @var string
     *
     * @ORM\Column(name="city", type="text")
     */
    private $city;

    /**
     * @var string
     *
     * @ORM\Column(name="country", type="text")
     */
    private $country;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="text", nullable=true)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="telephone", type="text", nullable=true)
     */
    private $telephone;

    /**
     * @var string
     *
     * @ORM\Column(name="history", type="text", nullable=true)
     */
    private $history;

    /**
     * @var string
     *
     * @ORM\Column(name="notes", type="text", nullable=true)
     */
    private $notes;

    /**
     * @var string
     *
     * @ORM\Column(name="eucharist", type="text", nullable=true)
     */
    private $eucharist;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="\CarpeDeumBundle\Entity\Time", mappedBy="place")
     */
    private $timetable;

    public function __construct()
    {
        $this->timetable = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updateAddress()
    {
        $this->address = $this->address1.' '.$this->address2.' '.$this->zipCode.' '.$this->city.' '.$this->country;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param string $type
     */
    public function setType($type)
    {
        $this->type = $type;
    }

    /**
     * @return string
     */
    public function getPic()
    {
        return $this->pic;
    }

    /**
     * @param string $pic
     */
    public function setPic($pic)
    {
        $this->pic = $pic;
    }

    /**
     * @return string
     */
    public function getPicCredits()
    {
        return $this->picCredits;
    }

    /**
     * @param string $picCredits
     */
    public function setPicCredits($picCredits)
    {
        $this->picCredits = $picCredits;
    }

    /**
     * @return string
     */
    public function getPics()
    {
        return $this->pics;
    }

    /**
     * @param string $pics
     */
    public function setPics($pics)
    {
        $this->pics = $pics;
    }

    /**
     * @return string
     */
    public function getPicsList()
    {
        return $this->picsList;
    }

    /**
     * @param string $picsList
     */
    public function setPicsList($picsList)
    {
        $this->picsList = $picsList;
    }

    /**
     * @return string
     */
    public function getVids()
    {
        return $this->vids;
    }

    /**
     * @param string $vids
     */
    public function setVids($vids)
    {
        $this->vids = $vids;
    }

    /**
     * @return string
     */
    public function getVidsList()
    {
        return $this->vidsList;
    }

    /**
     * @param string $vidsList
     */
    public function setVidsList($vidsList)
    {
        $this->vidsList = $vidsList;
    }

    /**
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @param string $address
     */
    public function setAddress($address)
    {
        $this->address = $address;
    }

    /**
     * @return string
     */
    public function getAddress1()
    {
        return $this->address1;
    }

    /**
     * @param string $address1
     */
    public function setAddress1($address1)
    {
        $this->address1 = $address1;
    }

    /**
     * @return string
     */
    public function getAddress2()
    {
        return $this->address2;
    }

    /**
     * @param string $address2
     */
    public function setAddress2($address2)
    {
        $this->address2 = $address2;
    }

    /**
     * @return string
     */
    public function getZipCode()
    {
        return $this->zipCode;
    }

    /**
     * @param string $zipCode
     */
    public function setZipCode($zipCode)
    {
        $this->zipCode = $zipCode;
    }

    /**
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param string $city
     */
    public function setCity($city)
    {
        $this->city = $city;
    }

    /**
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @param string $country
     */
    public function setCountry($country)
    {
        $this->country = $country;
    }

    /**
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * @param string $url
     */
    public function setUrl($url)
    {
        $this->url = $url;
    }

    /**
     * @return string
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * @param string $telephone
     */
    public function setTelephone($telephone)
    {
        $this->telephone = $telephone;
    }

    /**
     * @return string
     */
    public function getHistory()
    {
        return $this->history;
    }

    /**
     * @param string $history
     */
    public function setHistory($history)
    {
        $this->history = $history;
    }

    /**
     * @return string
     */
    public function getNotes()
    {
        return $this->notes;
    }

    /**
     * @param string $notes
     */
    public function setNotes($notes)
    {
        $this->notes = $notes;
    }

    /**
     * @return string
     */
    public function getEucharist()
    {
        return $this->eucharist;
    }

    /**
     * @param string $eucharist
     */
    public function setEucharist($eucharist)
    {
        $this->eucharist = $eucharist;
    }

    /**
     * @return ArrayCollection
     */
    public function getTimetable()
    {
        return $this->timetable;
    }

    /**
     * @param Time $time
     */
    public function addTimetable(Time $time)
    {
        $this->timetable[] = $time;

        return $this;
    }

    /**
     * @param Time $time
     */
    public function removeFolder(Time $time)
    {
        $this->timetable->removeElement($time);
    }
}

src/CarpeDeumBundle/Form/SearchType.php
<?php

namespace CarpeDeumBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('location', TextType::class, [
                'attr' => [
                    'placeholder' => 'Paris',
                ],
            ])
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => 'CarpeDeumBundle\Form\Model\SearchForm',
        ]);
    }

    public function getName()
    {
        return 'search_form';
    }
}

src/CarpeDeumBundle/Resources/views/Place/index.html.twig
{% extends 'CarpeDeumBundle::admin.html.twig' %}

{% block title %}Places{% endblock %}

{% block body %}
    <div class="row">
        {{ pagerfanta(places) }}

        <table class="u-full-width">
            <tbody>
                {% for place in places %}
                    <tr>
                        <td><a href="{{ path('place_show', {id: place.id}) }}">{{ place.id }}</a></td>
                        <td>{{ place.name|raw }}</td>
                        <td>{{ place.zipcode }}</td>
                        <td>{{ place.city }}</td>
                        <td>{{ place.country }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        {{ pagerfanta(places) }}
    </div>
{% endblock %}

src/CarpeDeumBundle/Resources/views/Place/show.html.twig
{% extends 'CarpeDeumBundle::admin.html.twig' %}

{% block title %}{{ place.name }} details{% endblock %}

{% block body %}
    <div class="row">
        <div class="four columns">
            <h1>{{ place.name }}</h1>
            <ul>
                <li>{{ place.address }}</li>
                <li>{{ place.telephone }}</li>
                <li><a href="{{ place.url }}">{{ place.url }}</a></li>
            </ul>
            <p>Histoire : {{ place.history }}</p>
            <p>Notes : {{ place.notes }}</p>
            <p>Messes : {{ place.eucharist }}</p>
        </div>
        <div class="four columns">
            <img width="264" height="264" src="//mediaauto.carpedeum.fr/300x300{{ place.pic }}">
        </div>
        <div class="four columns">
            <img src="https://api.mapbox.com/v4/mapbox.streets/pin-m-religious-christian+000({{ place.longitude }},{{ place.latitude }})/{{ place.longitude }},{{ place.latitude }},16/264x264.jpg70?access_token=pk.eyJ1IjoibGF1cmVudGdoIiwiYSI6IjdveXNkOEUifQ.F7qS-bIlU5-e23HB-SBDpA">
        </div>
    </div>
    <div class="row">
        <div class="one-half column">
            <table class="u-full-width">
                <thead>
                <tr>
                    <th>
                        <td colspan="2">Messes de semaine</td>
                    </th>
                </tr>
                </thead>
                {% for time in place.timetable if time.dayOfWeek < 6 %}
                    <tr>
                        <td>{{ constant('DAYS_OF_WEEK', time)[time.dayOfWeek] }}</td>
                        <td>{{ time.time|date('H:i') }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="one-half column">
            <table class="u-full-width">
                <th>
                    <td colspan="2">Week-end</td>
                </th>
                {% for time in place.timetable if time.dayOfWeek > 5 %}
                    <tr>
                        <td>{{ constant('DAYS_OF_WEEK', time)[time.dayOfWeek] }}</td>
                        <td>{{ time.time|date('H:i') }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}